### ISSUE TITLE
Trait's "as" statement not imported correctly

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#147]
See https://gist.github.com/Pittiplatsch/812e0cf1fa15660e78d6 - will extend the issue details once I've written tests for it.

/cc @Pittiplatsch

**Comment by DHager** [comment]
@Ocramius : As referenced [here](https://github.com/Ocramius/ProxyManager/issues/179#issuecomment-97982995), I encountered the  zendframework/zf2#6620 bug, and it seems to have been solved by forcing an dependency of `"zendframework/zend-code": ">=2.4.0"` within my project. 

However, it's just a hack, since my top-level project doesn't directly need/use `zendframework/zend-code`. Perhaps a future version of ProxyManager should specify  `">=2.4.0,<3.0`  directly?

**Comment by lon9man** [comment]
5 years are left. 
https://github.com/zendframework/zendframework/issues/6620 - CLOSED
do we have some progress?

**Comment by Ocramius** [comment]
Not sure what is being asked: this issue is closed, and ProxyManager relies on the latest zend-code release.

If there is a problem, please open a new issue with an example of a bug.

**Comment by lon9man** [comment]
sadly, but unable to easy migrate to ZF3.
it is as much as possible the latest versions:
```
zendframework/zendframework     2.5.3 
zendframework/zend-code         2.6.3 
ocramius/proxy-manager          1.0.2
```
now i have error like this https://github.com/zendframework/zendframework/issues/6620#issuecomment-94470000
do you know any solution to work proxy manager with ZF2?

**Comment by Ocramius** [comment]
You really need to upgrade your dependencies there, sorry.
