### ISSUE TITLE
Seperate Initializators for methods.

### ISSUE THREAD

**Issue by mimol91** [Ocramius/ProxyManager#164]
Hello. I am wondering how to set different initializers for methods.
For example methods getName needs to get data form DB, and getSurname needs to get data from external RESTful service.

Obviously I can fetch this data on getName or getSurname, but sometimes I dont need to know surname.

Can You tell me if there is a better way to achieve that than my solution

``` php
class Foo
{
    protected $foo;
    protected $bar;

    public function setFoo()
    {
        sleep(2);
        $this->foo = 'foo';
    }

    public function setBar()
    {
        sleep(1);
        $this->bar ='bar';
    }

    public function getFoo()
    {
        return $this->foo;
    }

    public function getBar()
    {
        return $this->bar;
    }
}

$startTime = microtime(true);
$factory   = new LazyLoadingGhostFactory();
$initializer = function ($proxy, $method, $parameters, & $initializer) {

    if ($method == 'getFoo' && !isset($proxy->fooInitialized)) {
        $proxy->fooInitialized = true;
        $proxy->setFoo('Hello World!');

    }

    if ($method == 'getBar' && !isset($proxy->barInitialized)) {
        $proxy->barInitialized = true;
        $proxy->setBar();

    }

    return true;

};


$instance = $factory->createProxy('Foo',$initializer);

var_dump('time after 1000 instantiations: ' . (microtime(true) - $startTime));
echo $instance->getBar();
echo $instance->getFoo();
echo $instance->getFoo();
var_dump('time after single call to doFoo: ' . (microtime(true) - $startTime));
```

**Comment by roxblnfk** [comment]
Hello. 
Is there a known way to lazy load each field separately?
I need to load each field individually when accessing it.

**Comment by Ocramius** [comment]
@roxblnfk

 * the initialiers are called when you attempt to access an un-initialized field
 * the initializer is called with the name of the field being accessed (see the result of `func_get_args()` in an initializer, or also https://github.com/Ocramius/ProxyManager/blob/21e2b4aa7d7661e7641cc6362fc8635ddcfa8464/src/ProxyManager/Factory/LazyLoadingGhostFactory.php#L78-L84

With this information, you can:

 * use the initializer to only initialize the field you care about
 * reset the initializer once you are done, so that access to other un-initialized fields is intercepted again
