### ISSUE TITLE
Proxying protected methods

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/ProxyManager#25]
Currently, the library only handles proxying of public properties.

It could be interesting to consider proxying also protected methods, but that's also (obviously) a violation of good OOP, since we then start doing assumptions on the internal API of an object.

It can be useful for debugging purposes though.

Changes required to make this happen are minimal though.

**Comment by HappyRay** [comment]
Hi @Ocramius 

I am using your library for my tool ( not open sourced yet ) to intercept calls to mock objects.

To support partial mocking, I need the ability to intercept protected method calls. Currently, I am forced to implement myself some of the features you have done. 

I understand partial mocking can be abused to violate good OOP. But there are legitimate usages of it although infrequent. For example, partial mocking support is needed when one public method calls another protected method of the same class and the developer wants to mock out the protected method.

It would be great if you can add this support. 

Thanks

Ray

**Comment by Ocramius** [comment]
@HappyRay it can be done, but the problem still remains: why would we do that? What is the exact use-case that cannot be replicated with public API?

**Comment by HappyRay** [comment]
@Ocramius thanks for the quick response.

My project is not open sourced yet. So it is a bit hard to explain without enough context. Let me try to add a bit more information to the example I mentioned above:

"For example, partial mocking support is needed when one public method calls another protected method of the same class and the developer wants to mock out the protected method.
"
I'd like to intercept protected method calls to the mocked object itself so that I can generate the correct partial mocking code. PHPUnit mocking framework can intercept protected method calls to support partial mocking.

**Comment by Ocramius** [comment]
> I'd like to intercept protected method calls to the mocked object itself so that I can generate the correct partial mocking code. PHPUnit mocking framework can intercept protected method calls to support partial mocking. 

Yes, but I don't know of a use-case where I would mock `protected` API instead of `public` API...

**Comment by HappyRay** [comment]
I can understand your hesitation. I encouraged my target users that it is best to test public methods only. However I find it a difficult task trying to change people's habit. In order to get my target users to take advantage of my tool, I decided to support the usage if they insist, while I am still actively discouraging people to do so.

**Comment by Ocramius** [comment]
I just checked around and I cannot implement this effectively, as it would only work with the scope localizer proxies, and with no wrappers

**Comment by HappyRay** [comment]
Got it. Thanks for looking into this.

**Comment by Ocramius** [comment]
Closing as "won't fix" here - this looked like a good idea at first, but in practice, `protected` methods should not exist at all from a "proxied API" PoV, and instead only exist in an object's `private` API (post-initialization, and not really supposed to be intercepted at all, since it's not a call from the outside).

Note that since even much older versions of `ocramius/proxy-manager`, it is possible to use property access interception to determine when to initialize an object (https://github.com/Ocramius/ProxyManager/tree/2.10.0/docs).

Ghost objects do not care if a property is accessed from `private` or `public` scope, and can be safely used when `protected` methods are involved.

As for intercepting calls: let's just not do it, since the call must come from a `public` scope somewhere anyway :-)
