### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by remicollet** [Ocramius/ProxyManager#322]
With PHP 5.6

Can't use version 2.0 (which depends on PHP 7)
Can't use version 1.0 with ZF 3

Will be nice to have a 1.x allowing zend-code 3

**Comment by Ocramius** [comment]
Won't work on 1.x anymore: it's security-only, sorry.

**Comment by Ocramius** [comment]
Ref: https://github.com/Ocramius/ProxyManager/blob/d3388430e109a3efd4bea2350226396b593e2d15/STABILITY.md#10x

**Comment by remicollet** [comment]
Sad that this make recent frameworks (SF 3 and ZF 3) unusable with PHP 5.6.

But if your happy with that, your decision.

**Comment by Ocramius** [comment]
@remicollet I am well aware of the introduced limitations. The decision of restricting supported PHP versions is also done on purpose, as maintaining code-generator libraries is a huge mess when it comes to language support.

I even had to release zend-code v3 myself in order to fix various codegen issues regarding PHP 7, introducing BC breaks on purpose to fix those problems.

I think pushing consumers to use newer dependencies when installing newer libraries is pretty much expected, if not even just basic responsible behavior by maintainers.
