### ISSUE TITLE
Lazy initializers turn proxy value-holder to a reference

### ISSUE THREAD

**Issue by nicolas-grekas** [Ocramius/ProxyManager#394]
A proxy initializer is a closure with this signature:
`function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy [...]);`

This closure is called to initialize a proxy using something like:
`$this->initializer->__invoke($this->valueHolder, $this [...]);`

If for some reason (circular ref, bad initializer, or PHP bug), the `$wrappedInstance` reference is not released, then the `$this->valueHolder` internal property keeps the "is_ref" internal flag "on", meaning eg all clones of the current proxy will share the same `$this->valueHolder` reference.

This is (one of?) the root issue that causes https://github.com/symfony/symfony/issues/23110.

As a work around to confirm the issue, I tried changing the `$instance->initializer = $initializer;` line in the `staticProxyConstructor()` method to that (quick and dirty, suffixes removed):
```php
        $instance->initializer = function ($dummy, ...$args) use ($instance, $initializer) {
            $initializer($value, ...$args);
            $instance->valueHolder = $value;
        };
```

This fixes https://github.com/symfony/symfony/issues/23110.

All versions of the package are affected.

**Comment by Ocramius** [comment]
@nicolas-grekas nasty one, but I don't think it can be fixed here. The `& $wrappedInstance` is by design, so that particular bit cannot be fixed. Would probably be interesting to have a test (seems like there is only a full repo to do that :-( ) and run it against various PHP versions to see if I can find a workaround.

The reason why the assignment is performed by-ref is because method calls to the proxy may still happen during initialization, which already needs to set a "real instance".

The API could be cleaned up by using a proper `ProxyInitializerInterface`, rather than a closure, but a reference would still be held somewhere.

Regardless of that (that's for `ProxyManager` 3.x, which isn't yet planned), this seems to be a refcount error in the engine itself, so it needs to be reduced to a smaller unit to be tested.

**Comment by nicolas-grekas** [comment]
There is a fix in fact, which involves adding a new method on generated proxies and call it instead of directly calling the closure (the new method would call the closure). I can try something.

**Comment by Ocramius** [comment]
@nicolas-grekas I'm more worried about getting a test scenario first :-\
