### ISSUE TITLE
Wrong error message from ProxyManager\Exception\FileNotWritableException on restricted directory

### ISSUE THREAD

**Issue by 2DSharp** [Ocramius/ProxyManager#414]
`ProxyManager\Exception\FileNotWritableException` outputs an error: **Could not write to path "path/to/cache/dir" : path does not exist** while the path clearly exists and but the application doesn't have write permissions on the directory. This is a misleading error message and should probably be showing "is not writable" instead.

**Comment by Ocramius** [comment]
Looking at the implementation of `FileNotWritableException`, the error messages are quite clear in `master`:

https://github.com/Ocramius/ProxyManager/blob/6a6c80849c27a9416512d3eee2dd85a9778a0fbc/src/ProxyManager/Exception/FileNotWritableException.php#L13-L33

Closing as "duplicate" here, since this has been fixed in https://github.com/Ocramius/ProxyManager/pull/438
