### ISSUE TITLE
Handle AISL proxies in Doctrine

### ISSUE THREAD

**Issue by kgrieco** [Ocramius/ProxyManager#436]
I'm building a new project and I'm using this package to wrap Doctrine entities using _Access Interceptor Scope Localizer_ proxies. However when I try to persist a proxy object I get (expected) error:

> The class 'XXX' was not found in the chain configured namespaces XXX

Is there a way to get rid of this problem?

**Comment by Ocramius** [comment]
Persisting a ProxyManager proxy through Doctrine ORM won't work unless you use the current `master` branch of `doctrine/orm`, where the proxy layer is already managed by ProxyManager.

Otherwise, Doctrine won't be able to do much in general, because it internally uses `get_class()` to figure out what you are giving to it, and `get_class()` will resolve to an unknown proxy type.

Replacing all those locations is probably not going to work, since there's a lot going on.

**Comment by Ocramius** [comment]
Actually, there is one location that transparently translates the `get_class()` calls: https://github.com/doctrine/persistence/blob/01c5f07bc091787b552d73669808defa7545720a/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php#L401-L413

You can try hacking into that, but you are quite out of the range of what the ORM usually deals with.

**Comment by kgrieco** [comment]
Ok thank you very much for information, I'm looking forward to Doctrine 3 :+1: 

In the meantime I'll try to fix it on my own...

**Comment by Ocramius** [comment]
Closing, since the question was answered.
