### ISSUE TITLE
How to force generation of a proxy?

### ISSUE THREAD

**Issue by mnapoli** [Ocramius/ProxyManager#440]
In PHP-DI we are implementing the generation of proxies at compile time (https://github.com/PHP-DI/PHP-DI/pull/645). So we need to generate proxy classes **without actually needing the proxy instances**.

What we had to do is overload the proxy generator to expose publicly the `protected generateProxy()` method:

https://github.com/PHP-DI/PHP-DI/pull/645/files#diff-c7c1194c4f1e314a097b1f91270a913fR15

That doesn't feel ideal. Is there a better solution to force generating the proxy class?

Reading [the documentation](https://ocramius.github.io/ProxyManager/docs/tuning-for-production.html) I see:

> Generating them "bulk" is not yet implemented

Note that I don't really want to generate them bulk, I already have a list of classes to proxy. I want to generate one at a time.

Thanks!

**Comment by Ocramius** [comment]
In `symfony/dependency-injection`, the proxies are dumped when the container is compiled. To do that, the DIC uses the proxy generator directly, rather than using one of the pre-configured `ProxyManager\Factory\*`.

See for example https://github.com/symfony/symfony/blob/v3.0.0/src/Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper.php

**Comment by Ocramius** [comment]
Note: ProxyDumper includes some hacks for stuff that wasn't yet fixed in here, because I am still lacking tests.

**Comment by mnapoli** [comment]
Thanks! It seems easier to simply generate a proxy instance instead (and not use the value).
