### ISSUE TITLE
Proxy file is generated although it already exists

### ISSUE THREAD

**Issue by olvlvl** [Ocramius/ProxyManager#531]
Hi,

We recently upgraded  to `mongodb-odm` v2 and we're facing an issue with the proxy generation. You see, we generate the hydrators and proxies before building our docker images, and the _cache_ folder is readonly after this point. `ProxyManager\Factory\AbstractBaseFactory::generateProxy()` uses `class_exists()` to determine if a proxy needs to be generated or not, and after this point it seems there's nothing that checks that the file actually needs to be generated, and the application crashed when the proxy manager tries to move the temporary file into the readonly cache folder.

https://github.com/Ocramius/ProxyManager/blob/4d7be24018475d2627ab74078e912ca9ef5887d2/src/ProxyManager/Factory/AbstractBaseFactory.php#L70

Could we modify the proxy generator to check if the file exists before it tries to create it? Or is there another solution?

**Comment by Ocramius** [comment]
This is part of the design of this component: https://github.com/Ocramius/ProxyManager/blob/master/docs/tuning-for-production.md#tuning-the-proxymanager-for-production

**Comment by Ocramius** [comment]
To clarify (in more detail) on what you should do:

 1. add a `classmap` entry pointing to your proxy dir
 2. generate proxies in the system that is assembling the deployment package/container
 3. run `composer dump-autoload -a`

A file existence check in the above factory is to be avoided, since it introduces unnecessary I/O, whereas your autoloader of choice is much more efficient and straightforward.

**Comment by olvlvl** [comment]
Using `classmap` fixed the issue. Thanks.

Now I'm wondering how proxies were autoloaded before?

**Comment by Ocramius** [comment]
ProxyManager has its own autoloader: https://github.com/Ocramius/ProxyManager/blob/4d7be24018475d2627ab74078e912ca9ef5887d2/src/ProxyManager/Configuration.php#L43
