### ISSUE TITLE
Breaking change as a non major release

### ISSUE THREAD

**Issue by ThibaultVlacich** [Ocramius/ProxyManager#621]
I noticed that you released version 2.9, containing a breaking change requiring Composer 2.0

```
    - ocramius/proxy-manager 2.9.0 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.9.0].
    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].
```

1/ Since this is a breaking change, it should have been released as a 3.0, because composer will resolve ^2.0.0 as 2.9.0
2/ Composer 2 is not even fully released, it's in alpha stages

So, please remove the 2.9.0 version and re-release it as 3.0.

**Comment by Ocramius** [comment]
Upgrading dependencies is not a BC break: none of the API of this package changed, and you will get the correct package version installed when running `composer update` on a system compatible to your production one.

Do not run `composer update` within a bleeding edge dev environment: that has always held true, even since compose `1.0.0-alpha1`

**Comment by ThibaultVlacich** [comment]
I'm sorry, but requiring Composer 2.0 IS a breaking change, especially considering that Composer 2.0 is NOT RELEASED and is only in alpha stages.

And this as nothing to do with "running composer update". If I create a new project from scratch, I will end up with same issue.

Here's Composer doc:
> The ^ operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example ^1.2.3 is equivalent to >=1.2.3 <2.0.0 as **none of the releases until 2.0 should break backwards compatibility**. For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.
>
> This is the recommended operator for maximum interoperability when writing library code.

"none of the releases until 2.0 should break backwards compatibility".
Forcing Composer 2.0 breaks backwards compatibility with Composer 1.0.

**Comment by Ocramius** [comment]
None of the API of this package is inherited from `composer/composer`, hence none of the API in here changed, therefore no BC break.

You are getting a SAT solver issue at dependency resolution, which is:

 1. Expected
 2. Good: it helps you figure out which dependencies still need work in order to be compatible with the latest `ocramius/proxy-manager`

I suggest you lock onto `^2.8`, which will give you a compatible dependency set.

**Comment by Ocramius** [comment]
You can read more about why upgrades are not BC breaks at https://github.com/Ocramius/PackageVersions/issues/105#issuecomment-516617164

Contains also references to the semver spec 👍
