### ISSUE TITLE
Get returned data of called method

### ISSUE THREAD

**Issue by hitriyvalenok** [Ocramius/ProxyManager#783]
I need to get result of the intercepted method. Something like that:
```php
function instantiateLoggableProxyOfVM()
{
    $factory = new LazyLoadingValueHolderFactory();
    return $factory->createProxy(
        VirtualMachine::class,
        function( &$wrappedObject, $proxy, $method, $parameters, &$initializer ) {
            $wrappedObject = new VirtualMachine();
            $initializer = null;

            $result = /* createFolder return value */;

            return true; // report success
        }
    );
}

$vm = instantiateLoggableProxyOfVM();
$vm->createFolder( '/builds' );
```

May I do it? Thanks!

**Comment by Ocramius** [comment]
For the lazy loading value holder proxies, initialization happens explicitly **before** the original method is called (otherwise, it can't be called at all).

This means that you cannot get the return value of the original `$vm->createFolder()` method here: that call happens **after** the closure has finished executing.

**Comment by hitriyvalenok** [comment]
Thanks for the reply! Can I implement it with ProxyManager someway?

**Comment by Ocramius** [comment]
Yes, but with other proxy types, not with a lazy-loading one.
